### ISSUE TITLE
n(>=2)개의 그래프 출력 관련 질문

### ISSUE THREAD

**Issue by Han-Jeong** [DSLDataStorage/DS_Project_3_2022_2#10]
안녕하세요 2020202047 미수강 이정한입니다.

txt파일로부터 그래프를 읽어오는 과정에서
그래프가 연결 그래프가 아닐 경우 여러 개의 그래프가 생성되는 것을
고려해야한다고 말씀하셨습니다.
bfs나 dfs의 경우를 예로, 출력을 할 때 시작 vertex를 통해 연결된
vertex를 차례로 출력하는 것으로 알고 있습니다. 
이때 2개 이상의 그래프가 생성 될 경우 출력은 연결된 vertex만을 출력하면 될까요
아니면 모든 vertex를 출력할 수 있도록 해주어야하나요
(예를 들어 시작 vertex가 0이고 사이즈가 6일때 4와 5는 연결되어있지만 다른 그래프와 연결되어있지 않는 상황
1. 0->1->2->3 출력
2. 0->1->2->3 / 4->5 출력)

감사합니다.

**Comment by DSLDataStorage** [comment]
시작 vertex가 주어진 탐색 방법이기 때문에 시작 vertex에 연결된 vertex 들만 방문 가능합니다.
따라서 1. 이 맞습니다.
