### ISSUE TITLE
FLOYD 출력에 관한 문의

### ISSUE THREAD

**Issue by hamoci** [DSLDataStorage/DS_Project_3_2022_2#11]
안녕하세요. 데이터구조설계, 실습(수78)을 수강중인 하준혁입니다.
별 것 아닌 질문이지만, 확인을 위해 문의 드립니다.
![image](https://user-images.githubusercontent.com/55676675/206860614-53c90ae7-6fb9-4956-99d2-c427bd9ffeca.png)

(1) FLOYD의 출력 형식의 이름이 PRINT로 되어있는데, 이는 오타가 아니라 의도된 사항인가요?
(2) [1][1]의 값이 0이 아닌 x인 것을 확인할 수 있는데, 다른 vertex처럼 [1][1]도 x가 아니라 0이어야 하는 것이 아닌지 궁금합니다.

감사합니다.

**Comment by DSLDataStorage** [comment]
두 부분 다 오타입니다.

**Comment by hamoci** [comment]
빠른 답변 감사드립니다.
