### ISSUE TITLE
kruskal sort사용 관련 질문

### ISSUE THREAD

**Issue by songyuri** [DSLDataStorage/DS_Project_3_2022_2#13]
안녕하세요 월요일 실습 수강 중인 2021202023 송유리입니다.
kruskal 알고리즘에 쓰이는 sort를 stl 사용이 아닌 함수를 직접 만드는걸로 자료에 나와있는데, stl 사용시, 감점이 이루어지는지 해당 명령어 0점 처리되는지 궁금합니다.
감사합니다.

**Comment by DSLDataStorage** [comment]
kruskal 알고리즘 부분은 점수가 부여되고, 정렬 알고리즘 부분에서 점수를 받지 못합니다.
