### ISSUE TITLE
Kruskal 명령어 출력 형식 문의

### ISSUE THREAD

**Issue by clickang** [DSLDataStorage/DS_Project_3_2022_2#14]
안녕하세요. 데이터 구조 실습 수요일 분반 수강중인 2021202051 강민영 입니다. kruskal 출력 형식에 대해 문의드립니다. 
<img width="582" alt="스크린샷 2022-12-13 오후 8 48 05" src="https://user-images.githubusercontent.com/107237936/207311177-c005f1ee-d831-4c20-9853-75aad7b5c6e7.png">
kruskal의 명령어 사용 및 기능 부분을 보면 MST를 구성하는 edge들의 weight 값을오름차순으로 출력 하라고 명시되어 있는데 
<img width="315" alt="스크린샷 2022-12-13 오후 8 48 17" src="https://user-images.githubusercontent.com/107237936/207311582-2821df51-4db6-4cbc-b0e3-913906a50cd0.png">
위의 출력 형식을 보면 weight에 따라 오름차순이 아닌 연결된 vertex에 따라 오름차순으로 출력이 된 것을 확인할 수 있습니다.  
weight에 따라 오름차순으로 출력해야 하는지 아니면 프로젝트 문서에 나온 그림대로 연결된 vertex의 번오에 따라 오름차순으로 출력해야 하는지 궁금합니다.

감사합니다.

**Comment by DSLDataStorage** [comment]
죄송합니다.
vertex의 오름차순으로 출력하시면 됩니다.

해당사항 감안하여 vertex 오름차순 혹은 weight 오름차순 둘 다 맞도록 채점하도록 하겠습니다.

**Comment by clickang** [comment]
넵 감사합니다.
