### ISSUE TITLE
출력 포맷 질문

### ISSUE THREAD

**Issue by gitSoyoungLee** [DSLDataStorage/DS_Project_3_2022_2#15]
안녕하세요. 금 실습 수강하는 2021202039 이소영입니다.
출력 포맷에 대해 질문이 있습니다.
Print Format에서는 아래와 같이 BFS, DFS, DFS_R에서 start vertex를 출력하는데
![image](https://user-images.githubusercontent.com/72489644/207508419-1f88a987-b1df-402a-9a67-57808859c5fc.png)
예시로 보여주신 실행 결과 및 화면에서는 start vertex가 출력되지 않습니다.
![image](https://user-images.githubusercontent.com/72489644/207508565-bff80914-bead-47f0-b6f3-c235b91f06bc.png)
어떤 걸 따라야할까요?

**Comment by DSLDataStorage** [comment]
방문 순서에 맞게 출력을 하시면 startvertex 출력은 크게 상관 없습니다.
