### ISSUE TITLE
2021202054 송예준 3차 플젝 관련 질문입니다~~

### ISSUE THREAD

**Issue by joon0723** [DSLDataStorage/DS_Project_3_2022_2#2]
안녕하세요 3차 플젝 문제 관련 질문이 있어서 issue에 올립니다~~ 혹시 KRUSKAL 명령어 부분에서 "MST를 구하는 과정 중 vertexSet 클래스를 이용하여 sub-tree가 circle을 이루는지에 대한 검사를 수행하도록 한다."라고 되어있는데 vertexSet class에 대한 설명이 따로 없어서 조금 혼란스럽습니다... 이것이 어떤 클래스인지 궁금합니다~~

**Comment by DSLDataStorage** [comment]
기존에 union, find 등의 함수를 vertexset 클래스에서 동작하도록 구현을 하였다가 수정하였습니다.
제안서에서는 해당부분이 수정 안 된 것 같습니다.
무시하고 진행하면 됩니다.
