### ISSUE TITLE
getAdjacentEdges() 관련 문의

### ISSUE THREAD

**Issue by sillindis** [DSLDataStorage/DS_Project_3_2022_2#3]
안녕하세요 과제 진행중에 궁금증이 생겨서 질문드렸습니다.

ListGraph Class, MatrixGraph Class의 멤버함수인  getAdjacentEdges() 는 무슨 함수이고 어떤 용도로 쓰이나요?

**Comment by DSLDataStorage** [comment]
인자로 입력된 vertex에 인접한 edge들을 map에 저장하는 함수입니다.
