### ISSUE TITLE
LOAD 에러 처리 관련 질문

### ISSUE THREAD

**Issue by N04hY** [DSLDataStorage/DS_Project_3_2022_2#4]
안녕하세요 컴퓨터정보공학부 2021202033 윤성민입니다. 

pdf 읽던 중 의문이 생겨 질문 남깁니다. 
4페이지의 LOAD 구현에 대한 내용 중, 2번째 체크 표시에는 그래프가 이미 구성되어 있는 경우 오류코드를 출력하도록 되어있고, 3번째 체크 표시에는 그래프 정보가 존재할 때 기존 정보를 삭제하고 새로 그래프를 생성한다고 명시되어 있습니다. 
![image](https://user-images.githubusercontent.com/101003842/205481753-a8744c48-2d9e-4626-831a-30c0d7617278.png)

세 번째 체크의 기존 그래프 정보가 존재한다는 것이 텍스트 파일을 의미하는 것인지, load를 통해 그래프를 구성한 상태를 의미하는 것인지 궁금합니다. 
전자의 경우 LOAD를 통해 그래프를 구성한 뒤에 텍스트파일을 삭제하는 것으로 해석되고, 후자의 경우라면 에러코드를 출력하는 대신 새로운 그래프를 구성하는 것으로 해석됩니다.

**Comment by DSLDataStorage** [comment]
세 번째 항목이 맞습니다.
제안서 수정하도록 하겠습니다.
새로 LOAD가 입력되면 새로 그래프를 생성해주세요.
