### ISSUE TITLE
graph_M 파일 구분자 문의

### ISSUE THREAD

**Issue by Alsguddd** [DSLDataStorage/DS_Project_3_2022_2#6]
안녕하세요 데이터구조실습 (월) 수강중인 2021202071 이민형입니다.

이전에 이슈를 보면 모든 파일의 구분은 스페이바로 한다고 하셨는데,
제안서를 보면 graph_M 파일을 보면 두 자리수를 넘어가는 숫자가 있는 부분은 
스페이스를 2번 사용한 것처럼 보이는데 그 점도 고려해야할까요?
아니면 모든 숫자들간의 구분은 스페이스바 한번으로 생각하면 될까요?
![image](https://user-images.githubusercontent.com/106859397/205835744-eea9ddbe-c053-4061-b011-24f60b8c896d.png)

감사합니다.

**Comment by DSLDataStorage** [comment]
해당 그림은 가독성을 위해 스페이스 2번으로 표시하였습니다.
실제 테스트에서는 스페이스 1번으로 구분하니 신경쓰지 않으셔도 됩니다.
