### ISSUE TITLE
방향성이 없는 그래프 연산에 대한 질문

### ISSUE THREAD

**Issue by hanoong7** [DSLDataStorage/DS_Project_3_2022_2#7]
안녕하세요 2021202061 류한웅입니다.
제안서를 보면, 그래프 연산중 BFS, DFS, KRUSKAL 연산의 경우에 방향성이 없다고 가정하고 연산을 수행하라는 내용이 있습니다.
하지만 graph_L(M).txt로 그래프를 생성할 경우에 방향성이 생길 수 밖에 없고,
이 때문에 인접한 edge를 구하는 과정에서도 반대 방향의 edge들은 포함되지 않는 문제가 발생해서 방향이 있는 그래프 연산으로 이루어집니다.
이를 해결하기 위해서 인접한 edge를 구하는 과정에서 해당 vertex가 가리키는 edge뿐만아니라 해당 vertex를 가리키는 다른 edge까지 모두 인접한 edge로 구하도록 기능을 추가 해야하는건지, 다른 방식의 접근, 해결 방법이 있는건지 궁금해서 질문드립니다.
감사합니다.

**Comment by DSLDataStorage** [comment]
방향성이 없도록 가정하여 처리하기 위해서는 추가적인 기능의 구현이 필요합니다.

인접한 edge를 구하는 과정에서 vertex로 들어오는 edge도 포함되도록 구현하시거나,
임시 그래프를 생성하여 방향성이 없도록 모든 edge를 복사하여 그래프 데이터를 저장하는 방법이 있습니다.

이외에도 다른 방법이 존재한다면 해당 방법을 이용하셔도 됩니다.

방향성이 없도록 edge를 복사하는 경우에서 만약 두 vertex를 연결하는 edge가 중복된다면 weight가 더 작은 edge를 사용하시면 됩니다.
