### ISSUE TITLE
List그래프에서의 edge가 없는 vertex(형식-1) 구현 질문

### ISSUE THREAD

**Issue by bbang-jun** [DSLDataStorage/DS_Project_3_2022_2#8]
안녕하세요. 수요일 실습 분반의 2019202023 강병준입니다.

프로젝트 spec에 의하면 2페이지에서 "List 그래프의 경우 (중략) 만약 edge가 없는 vertex의 경우 (형식-1)만 존재할 수 있다."
라고 명시되어 있는 부분이 있는데,  해당 부분을 반영하여 List 그래프를 PRINT 했을 때 어떤 형식으로 출력해야 해야하는지 궁금합니다.

ex) 만약 3이 edge가 없는 vertex라고 가정한다면 "[3] ->"으로 출력해야 할까요 아니면 edge가 없으므로 "[3]"만 출력하거나 아
예 해당 부분은 출력하지 말아야 할까요?

또한 List 그래프는 방향성을 가지고 구축을 합니다. 만약 edge가 없는 vertex 포함되고, edge가 없는 vertex 방향으로 edge가 존재하는 다른 vertex가 있게 되면 List 그래프가 여러 개 생성되는데, 이와 같이 그래프가 2개 이상인 사항 또한 고려해야 할까요?

ex)
0
1 2 // 1번째 그래프 생성
2 2
3 // 2번째 그래프 생성
4 2
4

마지막으로, Manager.cpp 내부에서 mBFS(), mDFS(), mDFS_R(), mDIJKASTRA(0, mKRUSKAL(), mBELLMANFORD(), mFLOYD() 함수가 이미 스켈레톤으로 주어져서 구현을 한 상태입니다. 
그런데 GraphMethod.cpp 내부에서도 똑같이 스켈레톤으로 함수가 그대로 주어졌는데, Manager.cpp에서 구현을 마치면 GraphMethod.cpp 파일에서는 구현을 따로 안 해도 되는 것이 맞을까요?
즉, Manger.cpp에서 주어진 스켈레톤 함수로 구현을 한 상황이면 GraphMethod.h와 GraphMethod.cpp 파일을 아예 사용하지 않아도 되는 것인지 궁금합니다.

질문에 대한 요약을 하자면 아래와 같습니다.

**1. List 그래프에서 edge 없는 vertex의 PRINT 형식
2. edge가 없는 vertex에 의해 그래프의 수가 2개 이상 형성되는 경우 고려 여부
3. Manager.cpp에서 주어진 함수로 구현 시 GraphMethod.h, GraphMethod.cpp 파일 미사용 가능 여부**

읽어주셔서 감사합니다.

**Comment by DSLDataStorage** [comment]
1. 그래프 출력의 경우 코드를 제공하였으니 코드를 그대로 이용하시면 됩니다.
2. 질문이 무슨 내용인지 잘 모르겠습니다.
3. 
그래프 연산은 GraphMethod 에서 수행하라고 제안서에 명시하였습니다. 
Manager에서는 GraphMethod의 함수를 호출하고 그래프 동작은 GraphMethod에서 동작하도록 코드를 작성하시기 바랍니다.
지키지 않을 시 불이익이 발생할 수 있습니다.

**Comment by bbang-jun** [comment]
2번 질문의 경우 아래의 L.txt 예시와 같은 상황에서 그래프가 2개가 구축되는 상황 또한 고려해야 하는지에 대한 내용입니다.

0
1 2 // 1번째 그래프 생성
2 2
3 // 2번째 그래프 생성
4 2 
4

**Comment by DSLDataStorage** [comment]
당연히 고려하셔야합니다.

**Comment by bbang-jun** [comment]
답변 감사합니다!
